### ISSUE TITLE
Cannot login with new LDAP account when auto-registration disabled (request invitation code)

### ISSUE THREAD

**Issue by Saruspete** [wekan/wekan-ldap#1]
## Issue

**Server Setup Information**:
* Wekan version: 1.39 + LDAP Package (installation done as taken from https://github.com/wekan/wekan/pull/1826/files)
* Operating System: CentOS 7

**Problem description**:
When Self-registration is disabled, account existing the ldap, but not on Wekan (never logged-in) cannot login as an invitation-code is requested.

``` javascript
// models/users.js
      throw new Meteor.Error('error-invitation-code-blank', 'The invitation code is required');
```

**Comment by xet7** [comment]
Please test newest LDAP in Docker:
https://github.com/wekan/wekan/wiki/LDAP
