### ISSUE TITLE
LDAP: unable to map CN to Fullname

### ISSUE THREAD

**Issue by xet7** [wekan/wekan-ldap#10]
I got this report from Stanalone Wekan Docker user:

Today I've been trying to map CN to Fullname:
```
LDAP_SYNC_USER_DATA_FIELDMAP={\"cn\":\"name\", \"mail\":\"email\"}
```
However, if I use the line as mentioned in the example (above) the login doesn't work anymore and the following is displayed in the log:
```
[INFO] User does not exist, creating "ehu"
[DEBUG] Identifying user with: sAMAccountName
Exception while invoking method 'login' SyntaxError: Unexpected token \ in JSON at position 1
at JSON.parse (<anonymous>)
at getDataToSyncUserData (packages/wekan:wekan-ldap/server/sync.js:116:27)
at addLdapUser (packages/wekan:wekan-ldap/server/sync.js:229:20)
at DDPCommon.MethodInvocation.<anonymous> (packages/wekan:wekan-ldap/server/loginHandler.js:159:18)
at packages/accounts-base/accounts_server.js:468:32
at tryLoginMethod (packages/accounts-base/accounts_server.js:245:14)
at AccountsServer.Ap._runLoginHandlers (packages/accounts-base/accounts_server.js:465:18)
at DDPCommon.MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:528:27)
at packages/check.js:128:16
at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
at Object._failIfArgumentsAreNotAllChecked (packages/check.js:127:41)
at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1765:18)
at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
```
The only way I don't get that error is if I leave out all the backslashes, eg:
```
- LDAP_SYNC_USER_DATA_FIELDMAP={"cn":"name", "mail":"email"}
```
but the Name doesn't get mapped.

@Akuket Can you look at this?

**Comment by xet7** [comment]
Moved to here from #15 

From @jolentes 

## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: most recent docker image from quay.io/wekan/wekan
* For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ?
* Wekan version: v1.69.0
* Operating System: Univention Corporate Server (debian 9)
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Apache 2 reverse proxy
* Node Version: v8.12.0
* MongoDB Version: docker mongo:3.2.21
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl): https://192.168.178.251/wekan

**Problem description**:
LDAP authentication is configured and works.
On a fresh DB and Wekan container started with docker-compose the user can login. The user account is created. Email address is synched.
The full name stayes empty! I tried to upload a screenshot but I was not able to.

I tried both settings for the mapping:
LDAP_SYNC_USER_DATA_FIELDMAP={"cn":"name", "mailPrimaryAddress":"email"}
LDAP_SYNC_USER_DATA_FIELDMAP={\"cn\":\"name\", \"mailPrimaryAddress\":\"email\"}

Log output on docker show this:
wekan-app  | [INFO] User does not exist, creating "firstname.lastname"
wekan-app  | [DEBUG] Identifying user with: uid 
wekan-app  | [DEBUG] Mapping field cn -> name 
wekan-app  | [DEBUG] user.name changed to: Firstname Lastname 
wekan-app  | [DEBUG] Mapping field mailPrimaryAddress -> email 
wekan-app  | [DEBUG] Identifying user with: uid 
wekan-app  | [DEBUG] New user data {
wekan-app  |   "username": "firstname.lastname",
wekan-app  |   "email": "firstname.lastname@example.com"
wekan-app  | }
wekan-app  | [INFO] Syncing user data 
wekan-app  | [DEBUG] user {
wekan-app  |   "email": "firstname.lastname@example.com",
wekan-app  |   "_id": "MJgtrqoRmNXfTzfHy"
wekan-app  | }
wekan-app  | [INFO] Idle 
wekan-app  | [INFO] Disconecting 
wekan-app  | [INFO] Closed 

I even tried:
LDAP_SYNC_USER_DATA_FIELDMAP={"cn":"fullname", "mailPrimaryAddress":"email"}
But then I get a debug message that the field fullname is not whitelisted.

How can the fullname be synced from LDAP?
Is there a list of user attributes documented that are availble for sync?

**Comment by xet7** [comment]
Moved to here from #12

From @vincowl

I am successfully using edge branch with LDAP. This is a great great work ! To push it a bit further, it would be great to have a way to map full name, is admin flag and avatar picture to LDAP fields.

**Comment by alkemyst** [comment]
Hello, everyone.
  I think I've got an idea on how to do this (provided that mapping an ldap field to the "fullname" property of the user does not pose any security threat.
  Nevertheless I have a different problem: I am using an openshift server and compose to load the software and I have no idea where the code is actually pulled from!
  Is there any simple way for me to edit the code that is running on an instance and test my patch? If so, I would be glad to contribute with a PR.

**Comment by xet7** [comment]
@alkemyst 

Simplest way is that you just add PR, and I will make new docker image tag for you, that you can try in OpenShift.

**Comment by xet7** [comment]
@alkemyst 

You can add PR to edge branch

**Comment by alkemyst** [comment]
Thanks for the help offer. Actually I need first a way to debug the code... can I do that on an openshift installation? Or should I install a local version to play with first (snap?).

**Comment by xet7** [comment]
@alkemyst 

For developing you can [Build from Source](https://github.com/wekan/wekan/wiki/Sourcehttps://github.com/wekan/wekan/wiki/Sourcehttps://github.com/wekan/wekan/wiki/Source).

**Comment by alkemyst** [comment]
I just have one more question: I forked wekan, now I want to compile it using wekan-ldap. How can I do that? Should I git clone wekan-ldap somewhere inside wekan?

Sorry for my ignorance :-)

**Comment by xet7** [comment]
@alkemyst 

```
git clone git@github.com:alkemyst/wekan.git
cd wekan
./releases/rebuild-wekan.sh
```
- First 1) install dependencies and then 2) rebuild.
- That rebuild-wekan.sh clones required directories and builds wekan.
- There is start-wekan.sh at wekan/releases or wekan/releases/virtualbox
- Add LDAP settings etc to start-wekan.sh, but uncomment all starting of wekan node etc
- Run that start-wekan.sh to get environment variables set to your current shell
- then on port you would like, for example:
```
cd wekan
meteor --port 4000
```
- at webbrowser go to http://localhost:4000
- now open directory wekan with Visual Studio Code, or any other editor you use. vscode has Meteor addons for syntax etc.
- if you make major changes, you may need to stop meteor and use rebuild-wekan.sh to rebuild again
- commit your changes and push to your fork
- at GitHub website click make pull request

**Comment by xet7** [comment]
@alkemyst 

It's not ignorance. Wekan info is all over the place, and wiki sometimes outdates, so you make fastest progress, when you ask any questions you have in mind immediately. See for example [this blog post](https://blog.wekan.team/2018/05/wekan-v1-00-released/index.html) what one newbie did.

**Comment by xet7** [comment]
Please test is this now fixed.

## Snap

```
sudo snap refresh wekan --beta --amend
```
If this then works with Fullname, I will release it to stable.

You can later change back to stable with:
```
sudo snap refresh wekan --stable --amend
```

## Docker

Use this image in docker-compose.yml:
```
image: quay.io/wekan/wekan:v1.74.1
```

**Comment by xet7** [comment]
Fix is from this PR: https://github.com/wekan/wekan-ldap/pull/18

**Comment by alkemyst** [comment]
I tested the image v1.74.1 and it works as intended.

**Comment by xet7** [comment]
@alkemyst 

Thanks for testing! I'll push it to everyone.

**Comment by Mystikal57** [comment]
Hello,
It doesn't work for me... fullname is blank avec account creation from ldap:
Dec 13 08:46:02 VWEB01 wekan.wekan[66812]: [DEBUG] userQuery {
Dec 13 08:46:02 VWEB01 wekan.wekan[66812]:   "username": "xusername"
Dec 13 08:46:02 VWEB01 wekan.wekan[66812]: }
Dec 13 08:46:02 VWEB01 wekan.wekan[66812]: [INFO] User does not exist, creating "xusername"
Dec 13 08:46:02 VWEB01 wekan.wekan[66812]: [DEBUG] Identifying user with: sAMAccountName
Dec 13 08:46:02 VWEB01 wekan.wekan[66812]: [DEBUG] Mapping field cn -> name
Dec 13 08:46:02 VWEB01 wekan.wekan[66812]: [DEBUG] user.name changed to: X NAME
Dec 13 08:46:02 VWEB01 wekan.wekan[66812]: [DEBUG] Mapping field mail -> email
Dec 13 08:46:02 VWEB01 wekan.wekan[66812]: [DEBUG] Identifying user with: sAMAccountName
Dec 13 08:46:02 VWEB01 wekan.wekan[66812]: [DEBUG] New user data {
Dec 13 08:46:02 VWEB01 wekan.wekan[66812]:   "email": "xusername@domain.com"
Dec 13 08:46:02 VWEB01 wekan.wekan[66812]: }
Dec 13 08:46:02 VWEB01 wekan.wekan[66812]: [INFO] Syncing user data
Dec 13 08:46:02 VWEB01 wekan.wekan[66812]: [DEBUG] user {
Dec 13 08:46:02 VWEB01 wekan.wekan[66812]:   "email": "xusername@domain.com",
Dec 13 08:46:02 VWEB01 wekan.wekan[66812]:   "_id": "d5ze2FGNpdvgRWjxu"
Dec 13 08:46:02 VWEB01 wekan.wekan[66812]: }

**Comment by alkemyst** [comment]
Hi @Mystikal57 
  you should be first sure to be able to connect to your LDAP server. I posted some suggestions here: https://github.com/wekan/wekan-ldap/issues/14
  Please let me know if this does not work for you.

**Comment by Mystikal57** [comment]
Hi, yes connection work, i'm able to connect with my ldap credentials

**Comment by alkemyst** [comment]
Did you test the syntax with ldapsearch and ldapwhoami as described in #14?

**Comment by Mystikal57** [comment]
Yes, i get all properties of my user with ldapsearch
