### ISSUE TITLE
Import and manage LDAP groups

### ISSUE THREAD

**Issue by vincowl** [wekan/wekan-ldap#11]
It would be great to have a way to define and mange groups in wekan. Therefore we could share boards with groups, which would be a lot easier for projects with an important team's turnover. If it  could be interfaced with LDAP groups, that would be a far lot better !!

**Comment by nerminator** [comment]
+1
I also need this feature. It would be very nice if we could map boards to LDAP groups. 

example: when a user in software group logs in,  he will be automatically added to software related boards. Or when a user is in IT group he will only be added to IT boards.

**Comment by xet7** [comment]
Hmm, I don't know what you mean with "Import LDAP group". In upcoming Teams feature LDAP group can be assigned to organization/team, and in general LDAP settings are managed in LDAP server management tools, and Wekan just uses the LDAP info when logging in.

Moved to https://github.com/wekan/wekan/issues/802
