### ISSUE TITLE
Sign In page inconsistancy

### ISSUE THREAD

**Issue by weeeezzll** [wekan/wekan-ldap#17]
I noticed an issue while trying to get LDAP logins setup. With LDAP login enabled, you get an Authentication dropdown box with "Password" and "LDAP" in it.

However, if you click the "Register" link, then from the registration page click "sign in", it brings you back to the sign in page, but the Authentication dropdown is no longer there.  if you refresh to login page, it comes back.

Also, is this Authentication dropdown suppose to still show up when you have LDAP_LOGIN_FALLBACK set to false?

**Comment by xet7** [comment]
Already fixed at https://github.com/wekan/wekan/pull/2003 by removing dropdown. Will be included in next release.
