### ISSUE TITLE
Cannot login with new LDAP account when auto-registration disabled (request invitation code)

### ISSUE THREAD

**Issue by patrickhedstrom** [wekan/wekan-ldap#29]
Same issue as #1 but using snap instead of docker

Server Setup Information:

    Wekan version: 1.82
    Operating System: Ubuntu 18.04

Problem description:
When Self-registration is disabled, account existing the ldap, but not on Wekan (never logged-in) cannot login as an invitation-code is requested.

`Dec 05 10:24:35 srv-wekan wekan.wekan[7379]: [ERROR] Error creating user {
Dec 05 10:24:35 srv-wekan wekan.wekan[7379]:   "isClientSafe": true,
Dec 05 10:24:35 srv-wekan wekan.wekan[7379]:   "error": "error-invitation-code-blank",
Dec 05 10:24:35 srv-wekan wekan.wekan[7379]:   "reason": "The invitation code is required",
Dec 05 10:24:35 srv-wekan wekan.wekan[7379]:   "message": "The invitation code is required [error-invitation-code-blank]",
Dec 05 10:24:35 srv-wekan wekan.wekan[7379]:   "errorType": "Meteor.Error"
`

**Comment by patrickhedstrom** [comment]
Yes, it did. First install was on the 25th of october (I don't know what stable version was out there at that time)

**Comment by rnck** [comment]
I testet with docker version. It worked with v1.75. It does not work anymore with v1.82 or newer.

I cannot test versions between 1.75 and 1.82 because there are no tags between these two versions https://hub.docker.com/r/wekanteam/wekan/tags/

**Comment by xet7** [comment]
Quay has all tags: quay.io/wekan/wekan

Also see [ChangeLog](https://github.com/wekan/wekan/blob/devel/CHANGELOG.md) at the time you mentioned.

If you find in what Wekan version changes did break it, it makes fixing easier.

**Comment by rnck** [comment]
I testet more versions with docker. With versions 1.76 to 1.78 LDAP login with new users still work.

v1.81 is missing "Authentication method" drop down, so no LDAP auth can be testet.

With v1.82 logs say:

```
[ERROR] Error creating user {
  "isClientSafe": true,
  "error": "error-invitation-code-blank",
  "reason": "The invitation code is required",
  "message": "The invitation code is required [error-invitation-code-blank]",
  "errorType": "Meteor.Error"
}
```

**Comment by xet7** [comment]
@rnck 

You should have drop down visible with this setting in newest Wekan v1.84:
```
- LDAP_ENABLE=true
```
Can you test is there still bug in Wekan v1.84 with this setting?

**Comment by rnck** [comment]
@xet7 Already testet "latest" version as of today. Now again with `image: quay.io/wekan/wekan:v1.84`. Dropdown is visible. Login does not work. Same error message as in v1.82:

```
[ERROR] Error creating user {
  "isClientSafe": true,
  "error": "error-invitation-code-blank",
  "reason": "The invitation code is required",
  "message": "The invitation code is required [error-invitation-code-blank]",
  "errorType": "Meteor.Error"
}
```

I did all my tests with same `docker-compose.yml` and changed only the image tags.

Please let me know if you need more information.

**Comment by xet7** [comment]
@rnck 

Thanks! I or @Akuket will look at this sometime.

**Comment by patrickhedstrom** [comment]
Saw that there was an update (1.85) but the issue remains. Any idea when it'll be fixed ? Sorry to be in a rush, but I've got users waiting to use wekan though ldap...
