### ISSUE TITLE
LDAP Logon with existing User : "Email already exists."

### ISSUE THREAD

**Issue by andyprv** [wekan/wekan-ldap#30]
## Wekan: v1.82  /  Docker on Ubuntu 18.04 Server 
---
If I delete the Database , Wekan creates new User with LDAP Logon.

But Wekan is running now for a while , with existing Users & lot of Boards , 
so I need to merge  the existing Users & there Boards.

Merge is activated:

     -e "LDAP_MERGE_EXISTING_USERS=true" \

```bash

[INFO] User does not exist, creating "aaaa.bbbbatwekan.com"
[DEBUG] Identifying user with: mail 

[DEBUG] New user data {
  "username": "aaaa.bbbbatwekan.com",
  "email": "aaaa.bbbb@wekan.com"
}
[ERROR] Error creating user {
  "isClientSafe": true,
  "error": 403,
  "reason": "Email already exists.",
  "message": "Email already exists. [403]",
  "errorType": "Meteor.Error"
}
```

**Comment by xet7** [comment]
@andyprv 

Please add comment to this issue what is the setting name and description, so I can fix it.

**Comment by andyprv** [comment]
there was nothing in the WEKAN Settings to Fix , 

The problem was the inconsistents of "usernames" in our User Database , 
caused by the "self-registration" of the users.

Everyone used a different "username" combination
