### ISSUE TITLE
Wekan LDAP Azure config docs to wiki?

### ISSUE THREAD

**Issue by xet7** [wekan/wekan-ldap#35]
@danpatdav

Can you add [docs to wiki](https://github.com/wekan/wekan/wiki/Azure
) how to configure Wekan LDAP on Azure? You mentioned about Azure at https://github.com/wekan/wekan/pull/2149

**Comment by danpatdav** [comment]
Yep.  As soon as I complete my testing and confirm it all works as expected, I'll update the docs.  If I don't respond in a week, nudge me.  :)

**Comment by danpatdav** [comment]
@xet7 Done.
